app/main/__init__.py
from flask import Blueprint, g


main = Blueprint('main', __name__, url_prefix='/<lang_code>')


@main.url_defaults
def add_language_code(endpoint, values):
    values.setdefault('lang_code', g.get('current_lang', 'uk'))


@main.url_value_preprocessor
def pull_lang_code(endpoint, values):
    lang_code = values.pop('lang_code')
    if lang_code not in ['en', 'uk']:
        lang_code = 'uk'
    g.current_lang = lang_code

from . import routes

app/main/routes.py
from flask import render_template, abort, redirect, url_for, g, request
from . import main
from ..models import Mural, Artist
from .. import config
import random


@main.route('/index')
def index():
    murals = Mural.query.all()
    mural_count = len(murals)
    artist_count = Artist.query.count()
    random_murals = random.sample(murals, min(len(murals), 4))
    return render_template('index.html',
                           title='Kyivmural',
                           murals=murals,
                           random_murals=random_murals,
                           mural_count=mural_count,
                           artist_count=artist_count)


@main.route('/mural/<int:mural_id>')
def mural(mural_id):
    mural = Mural.query.get(mural_id)
    if mural:
        return render_template('main/mural/detail_view.html',
                               mural=mural)
    else:
        abort(404)


@main.route('/murals')
@main.route('/murals/<int:page>')
def murals(page=1):
    if not isinstance(page, (int, long)):
        page = 1

    pagination = Mural.query.paginate(page, per_page=9, error_out=False)
    murals = pagination.items
    return render_template('main/mural/all.html',
                           murals=murals,
                           pagination=pagination)


@main.route('/artist/<int:id>')
def artist(id):
    artist = Artist.query.get(id)
    if mural:
        return render_template('main/artist/detail_view.html',
                               artist=artist)
    else:
        abort(404)


@main.route('/artists')
def artists():
    artists = Artist.query.all()
    return render_template('main/artist/all.html',
                           artists=artists)


@main.route('/about')
def about():
    return render_template('main/about/about.html')

app/templates/main/mural/all.html
{%  extends "base.html" %}

{% import "main/mural/macros.html" as macros %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static', filename='css/thumbnails.css')}}">
{%  endblock %}

{% block title %}
    {{ gettext('Murals') }}
{%  endblock %}

{%  block content %}
    <div class="container">
        <h1>
            {{ gettext('Murals') }}
        </h1>
        <br>

        {% for murals_chunk in murals|batch(3) %}
            <div class="row with-margin">
                {% for mural in murals_chunk %}
                    <div class="col-sm-4">
                        <a href="{{ url_for('main.mural', mural_id=mural.id) }}">
                            <div class="thumbnail no-margin" style="background-image: url('{{ url_for('static', filename='mural_img/' + mural.first_photo_name) }}')">
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}

        <div class="text-center">
            {{ macros.pagination_widget(pagination, 'main.murals') }}
        </div>
    </div>
{% endblock %}

app/templates/main/mural/detail_view.html
{%  extends "base.html" %}

{% set mural_description = mural.get_description(get_locale()) %}

{% block metas %}
    {{ super() }}
    <meta property="og:url" content="{{ request.url }}" />
    <meta property="og:type" content="place" />
    <meta property="og:title" content="Mural" />
    {% if mural_description %}
        <meta property="og:description" content="{{ mural_description }}" />
    {% endif %}
    <meta property="og:image" content="{{ url_for('static', filename='mural_img/' + mural.photos[0].file_name, _external=True) }}" />
    <meta property="place:location:latitude"  content="{{ mural.lat }}" />
    <meta property="place:location:longitude" content="{{ mural.lng }}" />

<meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@kyivmural" />
    <meta name="twitter:title" content="Kyivmural" />
    <meta name="twitter:description" content="{{ mural_description }}" />
    <meta name="twitter:image" content="{{ url_for('static', filename='mural_img/' + mural.photos[0].file_name, _external=True) }}" />
    <meta name="twitter:domain" content="kyivmural.com" />
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static', filename='css/mural_detail_view.css')}}">
{%  endblock %}

{% block scripts %}
    {{ super() }}
    <script src="http://maps.google.com/maps/api/js?key=AIzaSyBZbZ028Zs_V9dZbn9nEpAXNP27gJM4KGs"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/gmaps.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/twitter.js') }}"></script>
    <script>
        var map = new GMaps({
            el: '#mural_location',
            lat: {{ mural.lat }},
            lng: {{ mural.lng }},
            zoom: 15
        });
        map.addMarker({
            lat: {{ mural.lat }},
            lng: {{ mural.lng }}
        })
        map.setZoom( map.getZoom() );
    </script>
{% endblock %}

{%  block content %}
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=1717028235183199";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <!-- Mural description -->
                {% set mural_name = mural.get_name(get_locale()) %}
                {% if mural_name %}
                    <h1 class="no-top-margin">{{ mural_name }}</h1>
                {% endif %}

                {% if mural_description %}
                    <p class="lead text-justify">
                        {{ mural_description }}
                    </p>
                {% endif %}

                <!-- Mural photos -->
                {% for photo in mural.photos %}
                    <div class="row padding-15">
                    <div class="img-container">
                        <img src="{{ url_for('static', filename='mural_img/' + photo.file_name) }}" class="img-responsive center-block">
                    {% if photo.has_copyright %}
                        <p class="img-copyright"><small>{{ photo.copyright_string }}</small></p>
                    {% endif %}
                    </div>
                    </div>
                    <br>
                {% endfor %}
            </div>

            <div class="col-md-3 ">
                <div class="row padding-15">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">{{ gettext('Location') }} </h3>
                        </div>
                        <div class="panel-body">
                            <p>
                                {{ mural.get_address(get_locale()) }}
                            </p>
                            <p>
                                {{ mural.lat }}, {{ mural.lng }}

                            </p>
                            <p>
                                <div id="mural_location" style="width: 100%; height: 300px"></div>
                            </p>
                        </div>
                    </div>

                    {% if mural.artists|length > 0 %}
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">{{ gettext('Artist') }} </h3>
                            </div>
                            <div class="panel-body">
                                {% for artist in mural.artists %}
                                    <a href="{{ url_for('main.artist', id=artist.id) }}" class="btn btn-primary btn-block" role="button">{{ artist.full_name }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">{{ gettext('Be social') }} </h3>
                        </div>
                        <div class="panel-body">
                            <p>
                                <div class="fb-share-button" data-href="{{ request.url }}" data-layout="button_count" data-size="large" data-mobile-iframe="true">
                                    <a class="fb-xfbml-parse-ignore" target="_blank" href="{{ request.url }}">Share</a>
                                </div>
                            </p>
                            <p>
                                <a class="twitter-share-button" data-size="large" href="https://twitter.com/intent/tweet">Tweet</a>
                            </p>
                        </div>
                    </div>

                    {% if current_user.is_authenticated %}
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">{{ gettext('Admin area') }} </h3>
                            </div>
                            <div class="panel-body">
                                <form action="{{ url_for('admin.mural_update', id=mural.id) }}" method="post">
                                    <button type="submit" name="edit_form_button" class="btn btn-primary btn-block">Edit</button>
                                </form>
                                <br>
                                <form action="{{ url_for('admin.mural_delete', id=mural.id) }}" method="post">
                                    <button type="submit" class="btn btn-danger btn-block">Delete</button>
                                </form>
                            </div>
                        </div>
                    {%  endif %}

                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/main/mural/macros.html
{% macro pagination_widget(pagination, endpoint) %}
<ul class="pagination">
    <li {% if not pagination.has_prev %} class="disabled" {% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.page - 1, **kwargs) }}{% else %}#{% endif %}">
            &larr;
        </a>
    </li>
    {% for page in pagination.iter_pages() %}
        {% if page %}
            {% if page == pagination.page %}
                <li class="active">
                    <a href="{{ url_for(endpoint, page=page, **kwargs) }}">{{ page }}</a>
                </li>
            {% else %}
                <li>
                    <a href="{{ url_for(endpoint, page=page, **kwargs) }}">{{ page }}</a>
                </li>
            {% endif %}
        {% else %}
            <li class="disabled">
                <a href="#">
                    &hellip;
                </a>
            </li>
        {% endif %}
    {% endfor %}
    <li {% if not pagination.has_next %} class="disabled" {% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.page + 1, **kwargs) }}{% else %}#{% endif %}">
            &rarr;
        </a>
    </li>
</ul>
{% endmacro %}